<?php

namespace Louvres\CommandeBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    CONST MAX_PLACES_PAR_JOUR = 1000;
    function getDatesComplet()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('a.dateVisite');
        $qb->groupby('a.dateVisite');
        $qb->having('SUM(a.nbBillet) >= :maxPlaces');
        $qb->setParameter('maxPlaces', self::MAX_PLACES_PAR_JOUR);

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

/*    function getNbBillets($id)
    {
        $qb = $this->createQueryBuilder('c')
            ->addSelect('c')
            ->innerJoin('c.billets', 'billet')
            ->addSelect('COUNT(b.id) AS nbBillets')
            ->groupBy('c.id')
            ->where('c.id = :id_com')
            ->setParameter('id_com', $id);

        return $qb->getQuery()->getSingleScalarResult();
    }*/
}
