<?php

namespace Louvres\CommandeBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    CONST MAX_PLACES_PAR_JOUR = 1000;
    function getDatesComplet()
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a.dateVisite')
            ->where('a.status = :paye')
            ->groupby('a.dateVisite')
            ->having('SUM(a.nbBillet) >= :maxPlaces')
            ->setParameters(array('paye' => 'paye', 'maxPlaces' => self::MAX_PLACES_PAR_JOUR));

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    function getNbBillets($id)
    {
        $qb = $this->createQueryBuilder('c')
            ->innerJoin('c.billets', 'b')
            ->select('COUNT(b.id) AS nbBillets')
            ->where('c.id = :id_com')
            ->setParameter('id_com', $id);
        return $qb->getQuery()->getSingleScalarResult();
    }
}
