<?php

namespace Louvres\CommandeBundle\Repository;

/**
 * ConfirmationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfirmationRepository extends \Doctrine\ORM\EntityRepository
{
}

