sudo : false

language: php

cache:
    directories:
        $HOME/.composer/cache/files

php:
    - "5.6"
    - "7.0"
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

env:
    global:
        - MIN_PHP=5.6.21

before_install:
    - composer self-update --stable --no-interaction
    - composer install --no-interaction
    - export DISPLAY=:99
    - sh -e /etc/init.d/xvfb start
    - firefox --version
    - wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar
    - java -jar selenium-server-standalone-2.53.0.jar > /dev/null &
    - sleep 5
    - cp behat.yml.dist behat.yml
    - php bin/console server:start localhost:8080 --env=test --force

before_script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:create --env=test

script:
    - phpunit tests
    - php bin/behat features/confirmation.feature
    - php bin/behat features/homepage.feature
    - php bin/behat features/multiplescenarii.feature
