sudo : false

language: php

cache:
    directories:
        $HOME/.composer/cache/files

php:
    - "5.6"
    - "7.0"
    - "nightly"
    - "hhvm"

matrix:
    allow_failures:
        -php: nightly
        -php: hhvm

env:
    global:
        - MIN_PHP=5.6.21

before_install:
    - composer self-update --stable --no-interaction
    - composer install --no-interaction
    - wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar
    - java -jar selenium-server-standalone-2.47.1.jar > /dev/null &

script:
    - ./bin/phpunit tests