imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@LouvresCommandeBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

payum:
    security:
        token_storage:
            Louvres\CommandeBundle\Entity\PaymentToken: { doctrine: orm }
    storages:
        Louvres\CommandeBundle\Entity\Payment: { doctrine: orm }
        Louvres\CommandeBundle\Entity\PaymentDetails: { doctrine: orm }

    gateways:
        billets_paypal :
            factory: paypal_express_checkout
            username:  'philippine.chombart-facilitator_api1.gmail.com'
            password:  'SZPMQW4YKSKG8ZFE'
            signature: 'AdvVrWUW13YUjL9AW3PSyaDdhL6zAX-1uVeWGvpDdp3z--6Yi8TpwYEy'
            sandbox: true

        billets_stripe:
            factory: stripe_checkout
            publishable_key: 'pk_test_fLGAka6DVwEmTSiRPAQzDCbA'
            secret_key:      'sk_test_aIBk6ZsRhc7XYV5qlowNYzSh'
            payum.template.obtain_token: 'LouvresCommandeBundle:Commande:payumStripe.html.twig'

knp_snappy:
    pdf:
        enabled:    true
        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:    []
    image:
        enabled:    true
        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\""
        options:    []

knp_snappy:
    temporary_folder: %kernel.cache_dir%/snappy

nomaya_social :
    buttons:
        facebook:
            url:        null
            locale:     "fr_FR"
            send:       false
            width:      300
            showFaces:  false
            layout:     "button_count"
        twitter:
            url:        null
            locale:     "fr"
            message:    "Je veux partager cela avec vous"
            text:       "Tweet"
            via:        "Le musée du Louvres"
            tag:        "Venez avec moi !"

endroid_qr_code:
    size: 60
    padding: 10
    extension: gif
    error_correction_level: high
    foreground_color: { r: 0, g: 0, b: 0, a: 0 }
    background_color: { r: 255, g: 255, b: 255, a: 0 }