Louvres_commande_home:
        path:     /
        defaults: { _controller: LouvresCommandeBundle:Commande:home }

Louvres_commande_tarifs:
        path:     /tarifs
        defaults: { _controller: LouvresCommandeBundle:Commande:tarifs }

Louvres_commande_contact:
        path:     /contact
        defaults: { _controller: LouvresCommandeBundle:Commande:contact }

Louvres_commande_mentionsLegales:
        path:     /mentionslegales
        defaults: { _controller: LouvresCommandeBundle:Commande:mentions }

Louvres_commande_confirmation:
        path:     /confirmation/{code}
        defaults: { _controller: LouvresCommandeBundle:Commande:confirmation }
        requirements:
            code : .+

Louvres_commande_paiement_paypal:
        path:     /paiement/paypal/{code}
        defaults: { _controller: LouvresCommandeBundle:Payment:preparePaypalExpressCheckoutPayment }
        requirements:
            code : .+

Louvres_commande_paiement_stripe:
        path:     /paiement/stripe/{code}
        defaults: { _controller: LouvresCommandeBundle:Payment:prepareStripePayment }
        requirements:
            code : .+

Louvres_commande_paiement_done:
        path:     /paiement_done
        defaults: { _controller: LouvresCommandeBundle:Payment:captureDone }

